### ISSUE TITLE
Installation failed to create INI entries

### ISSUE THREAD

**Issue by rbri** [TomKrauss/pks-edit#16]
**Describe the bug**
* have downloaded Setup.PKS.Edit.exe Version 2.3.0 from github
* have started the installer - installation only for the current user without having admin rights

![image](https://github.com/TomKrauss/pks-edit/assets/2544132/a9af79a1-ae49-4da6-8d10-aca8f54f65a2)

Any installation logs i can provide?

**Comment by TomKrauss** [comment]
Hi Rbri, thank you for the report. I have published a new release 2.4.0 with a fixed installer, which should successfully complete in non-admin mode. May you can give the new release a try...

**Comment by rbri** [comment]
The 2.4.0 installer works great now. Many thanks!
