### ISSUE TITLE
Characters from the link are skipped in the preview

### ISSUE THREAD

**Issue by rbri** [TomKrauss/pks-edit#17]
![image](https://github.com/TomKrauss/pks-edit/assets/2544132/b9124fd6-8177-4fd3-b603-ce284f305bc5)

Looks like the first char is ignored...

(using the latest code from git)

**Comment by TomKrauss** [comment]
Thank you for finding this. What is this syntax [...] [...] supposed for however? Some kind of footnote syntax?

**Comment by rbri** [comment]
I guess these are named [Reference-style Links](https://www.markdownguide.org/basic-syntax/#reference-style-links)

When starting the document years ago i was not aware of the more common syntax so i started with this one. This style at least convenient if you have to point to the same urls several times or to have a nice list of links at the end of the document in case you have re-validate them.

**Comment by rbri** [comment]
The whole document is here https://raw.githubusercontent.com/HtmlUnit/htmlunit/master/README.md

**Comment by rbri** [comment]
@TomKrauss have compiled and tested your fix here - works fine - thanks.

**Comment by TomKrauss** [comment]
Reference-style links are now supported (at least in the most common forms).
