### ISSUE TITLE
Minor glitch in rendering image links

### ISSUE THREAD

**Issue by rbri** [TomKrauss/pks-edit#19]
I guess there is an off-by-one error ;-) when rendering image links. The open bracket is part of the link but the closing not.

![image](https://github.com/TomKrauss/pks-edit/assets/2544132/98db3f5b-771c-4076-b87d-850cdc2a5fa8)

The coloring in the editor is fine
![image](https://github.com/TomKrauss/pks-edit/assets/2544132/3a6c382b-8253-456b-a8fa-ee5f952721df)

**Comment by rbri** [comment]
with 2.7.0 we have now the preview - great progress

but now the editor is a bit broken
![image](https://github.com/user-attachments/assets/6e0d1161-eb16-4628-9c2f-76e35d2c29fa)

The coloring of the closing bracket is correct but the bold style is missing

**Comment by TomKrauss** [comment]
This will be hard to fix, as color coding in PKS Edit relies on regular expression matching, which is probably not powerful enough to handle those kind of tricky situations.

**Comment by rbri** [comment]
Ok, i think you can close this, because it is not a real problem and because i'm getting older i fear i will not be able to see the minor difference in the rendering in the near future.

**Comment by TomKrauss** [comment]
Closed as discussed.
