### ISSUE TITLE
Support (old) CUA keyboard shortcuts for clipboard access

### ISSUE THREAD

**Issue by rbri** [TomKrauss/pks-edit#20]
When editing text files i use the keyboard shortcuts for the clipboard the whole time. But because I'm old i use the CUA ones and i still think they are much better than the x-c-v stuff.

Is there any chance to support these shortcuts also in pks-edit? Currently some of them seems to trigger different actions....

![image](https://github.com/TomKrauss/pks-edit/assets/2544132/6677353b-148f-4b66-ba9d-b6947197e30e)

**Comment by TomKrauss** [comment]
Shortcuts and all kind of action bindings (menus etc...) are completely configurable in PKS-Edit: file pks_sys\pksactionbindings.json. Open Issue: there is currently no user specific way to extend/override the provided bindings. Something like placing a config file into $HOME/pks_sys/..., which will cause PKS Edit to load it from that directory rather than from the installed PKS_SYS directory.

**Comment by rbri** [comment]
ok, thanks

have added this

    {
      "key": "Shift+DELETE",
      "command": "@delete-selection"
    },
    {
      "key": "Ctrl+INSERT",
      "command": "@copy-to-clipboard"
    },
    {
      "key": "Shift+INSERT",
      "command": "@paste-clipboard"
    }

and it works fine in my first tests. But i think the name '@delete-selection' should mention the copy to clipboard - maybe something like '@cut-to-clipboard' to be similar to other two clipboard commands.

**Comment by TomKrauss** [comment]
Thank you - that is correct. I renamed the command to cut-to-clipboard.

**Comment by TomKrauss** [comment]
Should work now as expected. Also: user specific customization supported in the meanwhile.

**Comment by rbri** [comment]
Thanks a lot

**Comment by rbri** [comment]
Found the time to test do a real test on this (i had to cleanup my config first).
Looks like the delivered default config is still different from CUA. (Version 2.9.0)

| Attempt | PKS Edit | CUA |
| :---:   | :---: | :---: |
| Shift+DELETE | @delete-to-eol | @cut-to-clipboard |
| Ctrl+INSERT | @cut-selection | @copy-to-clipboard |
| Shift+INSERT | @paste-trash | @paste-clipboard |
