### ISSUE TITLE
makrdown preview eats characters when using head style

### ISSUE THREAD

**Issue by rbri** [TomKrauss/pks-edit#21]
![image](https://github.com/user-attachments/assets/a7a69a5d-ca94-4f81-b10e-2e6d984e8e60)

I hope the picture is enough... :-)

**Comment by TomKrauss** [comment]
Fixed - of course this should not eat up characters, but the behavior of writing #Header in markdown syntax is not completely specified. Should we accept this as a header? `# Header` is the recommended syntax for specifying headers.

**Comment by rbri** [comment]
I think the preview should not render this as header to force the user a bit to create correct markdown.
